### ISSUE TITLE
Fonte padrão

### ISSUE THREAD

**Issue by lucasferreira** [artinisc/Chat#1]
Opa,

Recomendo adicionar uma fonte padrão no BODY porque dai todo o "sistema" fica coberto em uma definição de fonte oficial (que não mude de usuário para usuário):

https://github.com/artinisc/Chat/blob/2fd21cb18739efa848a1087635656f68680ada86/css/index.css#L1-L5

Eu adicionaria uma linha assim:

```
font: 14px/21px Helvetica, Arial, sans-serif;
```

Ficando:

```css
body {
  font: 14px/21px Helvetica, Arial, sans-serif;
  margin: 0 auto; 
  background-image: url(../img/fundo_chat.webp); 
  background-size: 100%;
} 
```
